title: **********
logo: /assets/img/ADE98806-510F-4A5B-B4F1-6469EE9A57C2.png
description: SnapScraper is an open source intelligence tool which enables users to download media uploaded to Snapchatâ€™s Snap Map using a set of latitude and longitiude co-ordinates.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
github:
  release_url: https://github.com/rhematt/Snap-Scraper/releases/download/v0.5.1-b/SnapScraper
